# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install: 
  - Rscript -e 'install.packages(c("knitr", "lineprof"))'

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    - _R_CHECK_FORCE_SUGGESTS_: false